### ISSUE TITLE
More comprehensive alt-item-despawn-rate configuration

### ISSUE THREAD

**Issue by James-P-Bennett** [YouHaveTrouble/minecraft-optimization#130]
**Despawns common items every 30 seconds, very useful for servers with a lot of players and mob farms.**
Some more "uncommon" items, like iron and gold gear take 3 minutes.

```
   alt-item-despawn-rate:
      enabled: true
      items:
        # Common Mineral Blocks
        stone: 600
        granite: 600
        diorite: 600
        andesite: 600
        cobblestone: 600
        mossy_cobblestone: 600
        stone_slab: 600
        deepslate: 600
        cobbled_deepslate: 600
        netherrack: 600
        smooth_basalt: 600
        basalt: 600
        blackstone: 600
        end_stone: 600
        magma_block: 600
        prismarine: 600
        prismarine_bricks: 600
        dark_prismarine: 600
        # Logs
        oak_log: 600
        spruce_log: 600
        birch_log: 600
        jungle_log: 600
        acacia_log: 600
        dark_oak_log: 600
        mangrove_log: 600
        cherry_log: 600
        crimson_stem: 600
        warped_stem: 600
        stripped_oak_log: 600
        stripped_spruce_log: 600
        stripped_birch_log: 600
        stripped_jungle_log: 600
        stripped_acacia_log: 600
        stripped_dark_oak_log: 600
        stripped_mangrove_log: 600
        stripped_cherry_log: 600
        stripped_crimson_stem: 600
        stripped_warped_stem: 600
        # Saplings
        oak_sapling: 600
        spruce_sapling: 600
        birch_sapling: 600
        jungle_sapling: 600
        acacia_sapling: 600
        dark_oak_sapling: 600
        mangrove_propagule: 600
        cherry_sapling: 600
        # Natural Blocks
        dirt: 600
        coarse_dirt: 600
        rooted_dirt: 600
        moss_block: 600
        moss_carpet: 600
        podzol: 600
        mycelium: 600
        grass_block: 600
        gravel: 600
        sand: 600
        red_sand: 600
        soul_sand: 600
        soul_soil: 600
        mud: 600
        clay: 600
        sandstone: 600
        red_sandstone: 600
        cut_sandstone: 600
        cut_red_sandstone: 600
        smooth_sandstone: 600
        smooth_red_sandstone: 600
        terracotta: 600
        white_terracotta: 600
        orange_terracotta: 600
        magenta_terracotta: 600
        light_blue_terracotta: 600
        yellow_terracotta: 600
        lime_terracotta: 600
        pink_terracotta: 600
        gray_terracotta: 600
        light_gray_terracotta: 600
        cyan_terracotta: 600
        purple_terracotta: 600
        blue_terracotta: 600
        brown_terracotta: 600
        green_terracotta: 600
        red_terracotta: 600
        black_terracotta: 600
        sculk: 600
        sculk_catalyst: 600
        sculk_vein: 600
        # Leaves
        oak_leaves: 600
        spruce_leaves: 600
        birch_leaves: 600
        jungle_leaves: 600
        acacia_leaves: 600
        dark_oak_leaves: 600
        mangrove_leaves: 600
        cherry_leaves: 600
        azalea_leaves: 600
        flowering_azalea_leaves: 600
        # Mushrooms
        brown_mushroom: 600
        red_mushroom: 600
        brown_mushroom_block: 600
        red_mushroom_block: 600
        mushroom_stem: 600
        mushroom_block: 600
        # Vines
        vines: 600
        twisting_vines: 600
        weeping_vines: 600
        glow_lichen: 600
        # Flowers
        dandelion: 600
        poppy: 600
        blue_orchid: 600
        allium: 600
        azure_bluet: 600
        red_tulip: 600
        orange_tulip: 600
        white_tulip: 600
        pink_tulip: 600
        oxeye_daisy: 600
        cornflower: 600
        lily_of_the_valley: 600
        wither_rose: 600
        sunflower: 600
        lilac: 600
        rose_bush: 600
        peony: 600
        flowering_azalea: 600
        # Seeds
        wheat_seeds: 600
        melon_seeds: 600
        pumpkin_seeds: 600
        beetroot_seeds: 600
        cocoa_beans: 600
        nether_wart: 600
        # Farming
        kelp: 600
        bamboo: 600
        cactus: 600
        chorus_fruit: 600
        beetroot: 600
        potato: 600
        carrot: 600
        sweet_berries: 600
        glow_berries: 600
        poisonous_potato: 600
        apple: 600
        # Mob Drops
        rotten_flesh: 600
        bone: 600
        string: 600
        spider_eye: 600
        gunpowder: 600
        ender_pearl: 600
        blaze_powder: 600
        ghast_tear: 600
        magma_cream: 600
        phantom_membrane: 600
        shulker_shell: 600
        blaze_rod: 600
        slime_ball: 600
        ink_sac: 600
        glow_ink_sac: 600
        rabbit_hide: 600
        rabbit_foot: 600
        feather: 600
        egg: 600
        # Wooden Gear
        wooden_sword: 600
        wooden_shovel: 600
        wooden_pickaxe: 600
        wooden_axe: 600
        wooden_hoe: 600
        wooden_helmet: 600
        wooden_chestplate: 600
        wooden_leggings: 600
        wooden_boots: 600
        # Stone Gear
        stone_sword: 600
        stone_shovel: 600
        stone_pickaxe: 600
        stone_axe: 600
        stone_hoe: 600
        stone_helmet: 600
        stone_chestplate: 600
        stone_leggings: 600
        stone_boots: 600
        # Iron Gear
        iron_sword: 3600
        iron_shovel: 3600
        iron_pickaxe: 3600
        iron_axe: 3600
        iron_hoe: 3600
        iron_helmet: 3600
        iron_chestplate: 3600
        iron_leggings: 3600
        iron_boots: 3600
        # Gold Gear
        golden_sword: 3600
        golden_shovel: 3600
        golden_pickaxe: 3600
        golden_axe: 3600
        golden_hoe: 3600
        golden_helmet: 3600
        golden_chestplate: 3600
        golden_leggings: 3600
        golden_boots: 3600
        # Leather Gear
        leather_helmet: 600
        leather_chestplate: 600
        leather_leggings: 600
        leather_boots: 600
        # Chainmail Gear
        chainmail_helmet: 600
        chainmail_chestplate: 600
        chainmail_leggings: 600
        chainmail_boots: 600
        # Misc Trash
        stick: 600
        bone_meal: 600
        saddle: 600
        snowball: 600
        iron_nugget: 600
        bowl: 600
        prismarine_shard: 600
        prismarine_crystals: 600
```
