### ISSUE TITLE
New config add

### ISSUE THREAD

**Issue by Pantera07** [YouHaveTrouble/minecraft-optimization#58]
bukkit.yml
https://github.com/YouHaveTrouble/minecraft-optimization#spawn-limits
```
spawn-limits:
  monsters: 70
  animals: 10
  water-animals: 5
  water-ambient: 20
  water-underground-creature: 5
  ambient: 15
```
Add 'water-underground-creature'

https://github.com/YouHaveTrouble/minecraft-optimization#ticks-per
```
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  water-spawns: 1
  water-ambient-spawns: 1
  water-underground-creature-spawns: 1
  ambient-spawns: 1
  autosave: 6000
```
Add 'water-underground-creature-spawns'

There is a new entry in the bukkit.yml config so you need to add optimizations.
